### PR TITLE
Sync release with dev

### PR DESCRIPTION
**Pull request by mpgxvii**
- Sync release with dev

### CODE REVIEW

**Comment by Bdegraaf1234** [comment]
@mpgxvii If I could, I would like to bump some dependencies before this release. I will do it now :)

**Comment by Bdegraaf1234** [comment]
Oops, this would require the new mp release (2.1.1, just before 3.0) which requires @pvannierop to finish the update.

It would take until monday at least, if you cannot wait until then just go ahead otherwise I will make a PR

**Comment by mpgxvii** [comment]
> Oops, this would require the new mp release (2.1.1, just before 3.0) which requires @pvannierop to finish the update.
> 
> It would take until monday at least, if you cannot wait until then just go ahead otherwise I will make a PR

Hi @Bdegraaf1234 this has already been released a few days ago. 😅 But yes please make a PR for the updates. Thank you!

**Comment by Bdegraaf1234** [comment]
@mpgxvii so should we merge/close this?

**Pull request merged**
